---
title: Bristol DUG
subtitle: The Bristol Drupal User Group.
email: info@drupalbristol.org.uk
default_date_format: jS F
fuzzy_date_format: F

github:
    url: https://github.com/drupal-bristol/drupalbristol.org.uk

imports:
    - venues.yml
    - events.yml
    - speakers.yml

sponsors:
    sift:
        name: Sift
        website: http://www.sift.com/

    microserve:
        name: Microserve
        website: https://microserve.io/

    halo:
        name: Halo
        website: http://wearehalo.co.uk/
