---
sculpin:
    ignore:
        - "**/*.min.css.map"
sculpin_content_types:
    posts:
        enabled: false
    speakers:
        permalink: speakers/:slug_title/
    talks:
        permalink: talks/:slug_title/
